#https://nginx.org/

#用户权限
user nobody;

#允许最大进程数(自动根据CPU核心数设置)
worker_processes 2;

#保存进程ID
pid /tmp/nginx.pid;

#错误日志监控
error_log /tmp/nginx-error.log crit;

#模块定义
include module.d/*.module;

#允许每个进程最大连接数
events {
	worker_connections 16;
}

#默认配置项
http {
	server_tokens off; #隐藏Nginx版本号
	proxy_hide_header X-Powered-By; #隐藏后端服务器信息
	proxy_hide_header Server;#隐藏服务器信息

	#关闭访问日志监控
	access_log off;

	log_format main
		'$request_method $scheme://$host$request_uri => $status'
		' (${body_bytes_sent}B in ${request_time}s) <- $http_referer';

	include mime.types; #包含MIME类型定义文件
	default_type application/octet-stream; #设置默认MIME类型
	sendfile on; #启用sendfile系统调用

	# 超时设置(防御DoS攻击)
	client_body_timeout 10;
	client_header_timeout 10;
	keepalive_timeout 15;
	send_timeout 10;

	# 缓冲区限制（防止缓冲区溢出攻击）
	client_max_body_size 2M; #允许最大文件上传
	client_body_buffer_size 128K; #请求体缓冲区
	client_header_buffer_size 4k; #请求头缓冲区
	large_client_header_buffers 4 8k; #大请求头缓冲区

	# 文件访问限制
	autoindex off; #禁止目录遍历

	#首页
	server {
		server_name localhost;
		listen 8866;
		listen [::]:8866;

		location / { 
			root /opt/etc/www; #根目录
            		index index.html index.htm index.php; #默认页
		}

		location ~ \.php(.*) {
			fastcgi_pass unix:/tmp/nginx.sock;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include fastcgi_params;
		}
	}

	#SSL
	#server {
		#server_name localhost;
		#listen 443 ssl;
		#listen [::]:443 ssl;
		#ssl_certificate *.crt;
		#ssl_certificate_key *.key;
		#ssl_session_cache shared:SSL:1m;
		#ssl_session_timeout 5m;

		#location / { #默认页
			#default_type text/html;
			#root /opt/etc/www;
			#index index.html index.htm index.php;
		#}
	#}

	include conf.d/*.conf; #定义其他配置项
}