[www]

;监听配置
user=nobody				;以低权限用户运行
group=nobody				;以低权限用户组运行
listen=/tmp/nginx.sock			;监听套接字路径
listen.owner=nobody			;监听用户
listen.group=nobody			;监听用户组
listen.mode=0660			;监听权限(读写)

;进程管理
pm=dynamic
pm.max_children=2			;最大2个进程
pm.start_servers=1			;启动1个
pm.min_spare_servers=1			;保持至少1个空闲
pm.max_spare_servers=2			;最多保留2个空闲

;提升安全性
catch_workers_output=yes		;捕获输出并重定向到PHP-FPM的主日志
decorate_workers_output=no		;控制是否在捕获的日志前添加进程标识前缀