### Configuration Syntax
# https://wiki.lighttpd.net/Docs_Configuration
### Configuration Options
# https://wiki.lighttpd.net/Docs_ConfigurationOptions

#监听配置
server.port = 8866 #端口号务必跟IPv4保持一致(是个BUG)
#IPv4
$SERVER["socket"] == ":8866" {
	#IPv4配置块
}
#IPv6
$SERVER["socket"] == "[::]:8866" {
	#IPv6配置块
}

#网页根目录(访问的网页存放路径)
server.document-root = "/koolshare/configs/lighttpd/www/"

#修改或删除响应头中的服务器标识
server.tag = ""

#访问错误跳转
server.error-handler-404 = "/404.html"

#禁止访问特定文件(mod_access模块)
$HTTP["url"] =~ "\.(htaccess|conf|sh|log)$" {
	url.access-deny = ( "" )
}

#默认页(mod_indexfile模块)
index-file.names = ( "index.html", "index.htm", "default.html", "default.htm" )

#禁止直接访问特定文件(返回403 Forbidden)
static-file.exclude-extensions = (
	".php",			# PHP 源码
	".phps",		# PHP 源码
	".inc",			# PHP 包含文件
	".log",			# 日志文件
	".txt",			# 文本文件可选）
	".sh",			# Shell 脚本
	".pl",			# Perl 脚本
 	".py",			# Python 脚本
	".conf",		# 配置文件
	".htaccess",	# Apache配置文件
	".bak",			# 备份文件
	".old",			#旧文件	
	".sql"			# 数据库文件
)

#阻止恶意扫描或爬虫(mod_rewrite模块)(先重写再拒绝)
url.rewrite-once = (
	".*\.(sql|bak|old)$" => "/block"
)
$HTTP["url"] =~ "^/block" {
	url.access-deny = ( "" )
}

#服务记录
server.pid-file = "/koolshare/configs/lighttpd/lighttpd.pid"
server.errorlog = "/koolshare/configs/lighttpd/lighttpd.log"

#其他配置
include "/koolshare/configs/lighttpd/mime.conf"

#模块扩展(搭配PHP-CGI)
server.modules += (
	"mod_rewrite",
	"mod_access"
)
