[PHP]
;启用 PHP 引擎
engine = On
;安全性可选项，限制PHP脚本中可以打开的文件或目录的范围
open_basedir = "/opt/etc/www/:/tmp/"
;指定 Web 服务器的文档根目录
doc_root = "/opt/etc/www/"
;扩展插件路径
extension_dir = "/opt/lib/php8"
;浮点数显示精度
precision = 12
;是否启用输出缓冲
output_buffering = Off
;是否自动压缩 HTML 输出
zlib.output_compression = Off
;每次输出后是否强制刷新缓冲区
implicit_flush = Off
;当反序列化遇到未定义类时调用的函数
unserialize_callback_func =
;对浮点数的精度
serialize_precision = 100
;禁用函数
;disable_functions = exec, passthru, shell_exec, system, proc_open, popen, phpinfo
;禁用特定类
disable_classes =
;显示php版本号
expose_php = Off
;脚本最大执行时间(秒)
max_execution_time = 30
;接收POST/GET数据的最大时间
max_input_time = 60
;单个脚本最大内存
memory_limit = 8M
;报告所有错误，但忽略“未定义变量”和“已废弃”警告
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED
;显示错误信息输出到页面
display_errors = Off
;启动阶段显示错误(如扩展加载失败)
display_startup_errors = Off
;是否记录错误到日志
log_errors = Off
;是否忽略重复错误
ignore_repeated_errors = Off
ignore_repeated_source = Off
;报告内存泄漏
report_memleaks = On
;将最后一条错误存入
track_errors = Off
;初始化超全局变量的顺序
variables_order = "EGPCS"
;$_REQUEST的组成仅(GET+POST,不含Cookie更安全)
request_order = "GP"
;启用$argc/$argv命令行参数
register_argc_argv = On
;延迟初始化 $GLOBALS等节省内存
auto_globals_jit = On
;提交POST数据大小
post_max_size = 1M
;自动预置文件
auto_prepend_file =
auto_append_file =
;默认响应头
default_mimetype = "text/html"
;用户目录功能
user_dir =
;允许在运行时使用动态加载扩展
enable_dl = Off
;尝试解析 PATH_INFO
cgi.fix_pathinfo = 0
;允许HTTP文件上传
file_uploads = Off
;上传时文件临时存储目录
upload_tmp_dir = "/opt/tmp"
;单个上传文件的最大大小
upload_max_filesize = 2M
;单次请求最多上传文件数量
max_file_uploads = 5
;允许执行URL打开文件
allow_url_fopen = Off
;允许执行URL引用头部文件
allow_url_include = Off
;默认socket流如fsockopen、file_get_contents的默认超时时间(秒)
default_socket_timeout = 60